sudo: required
language: node_js
node_js: '12'

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      install:
        - brew update
        - brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
        - brew install yarn
      addons:
        chrome: stable
    - os: linux
      dist: xenial
      language: generic
      services:
        - docker
#      before_install:
#        - export CHROME_BIN=chromium-browser
#        - export DISPLAY=:99.0
#        - sh -e /etc/init.d/xvfb start

addons:
  ssh_known_hosts:
    - the-front-end.de
    - frs.sourceforge.net
  apt:
    packages:
      - sshpass
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder


script:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      PUB=always
    else
      PUB=never
    fi
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      echo '____RUNNING DOCKER____'
      docker run $ENVS --rm \
        $(env | \
        grep -Eo '^[^\s=]*(_TOKEN|_KEY)[^\s=]*' | \
        sed '/^$/d;s/^/-e /' | \
        paste -sd ' ' \
        ) \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine-chrome \
        /bin/bash -c "echo '____DOCKER_INNER_START____' && ls -l &&  yarn --link-duplicates --pure-lockfile && yarn run distLinuxAndWin -p ${PUB} && ls -l ./dist"
    else
      yarn install && yarn add 7zip-bin-mac
      yarn run dist -p $PUB
    fi

deploy:
  - provider: snap
    snap: ./app-builds/*.snap
    channel: edge
    skip_cleanup: true
    on:
      tags: false
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: snap
    snap: ./app-builds/*.snap
    channel: candidate
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
      tags: true
  - provider: script
    script: sshpass -p "$DEPLOY_PASS" rsync -avz ./dist $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
      tags: true
# NOTE: this would only work, if we could auto publish the github draft
#  - provider: script
#    script: brew update && brew install vitorgalvao/tiny-scripts/cask-repair && openssl aes-256-cbc -K $encrypted_c04542ca1075_key -iv $encrypted_c04542ca1075_iv -in build/hub.enc -out ~/.config/hub -d && cask-repair -b -v $TRAVIS_TAG superproductivity
#    skip_cleanup: true
#    on:
#      branch: master
#      condition: $TRAVIS_OS_NAME = osx
#      tags: true
